@host = http://localhost:8080/apex-bank
@base = /api 
@accounts = {{base}}/accounts
@accountNumber = 10119

### CHECK BALANCE
POST {{host}}{{accounts}}/{{accountNumber}}/balance
Content-Type: application/json 

{
    "pin": 1234
}


### DEPOSIT
POST {{host}}{{accounts}}/{{accountNumber}}/deposit
Content-Type: application/json

{
    "pin": 1234,
    "amount": 200
}

### WITHDRAW
POST {{host}}{{accounts}}/{{accountNumber}}/withdraw
Content-Type: application/json 

{
    "pin": 1234,
    "amount": 2000
}

### MINI STATEMENT
POST {{host}}{{accounts}}/{{accountNumber}}/transactions
Content-Type: application/json 

{
    "pin": 1234,
    "limit": 5
}
