@host = http://localhost:8080/apex-bank
@base = /api 
@users = {{base}}/users



### CREATE USER
POST {{host}}{{users}}
Content-Type: application/json

{
    "fullName": "Bright Asante",
    "email": "bright.asante@yahoo.com",
    "password": "amen"
}

### LOGIN
POST {{host}}{{users}}/login
Content-Type: application/json 

{
    "email": "bright.asante@yahoo.com",
    "password": "amen"
}


### CREATE SAVINGS ACCOUNT

@userId = 9
POST {{host}}{{users}}/{{userId}}/accounts
Content-Type: application/json  

{
    "type": "SAVINGS", 
    "initialDeposit": 350,
    "pin": 1234
}


### CREATE CURRENT ACCOUNT

POST {{host}}{{users}}/{{userId}}/accounts
Content-Type: application/json 

{
    "type": "CURRENT",
    "initialDeposit": 50,
    "pin": 1234
}


### List User Accounts

GET {{host}}{{users}}/{{userId}}/accounts

